# Generated by Django 4.2.3 on 2023-09-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='usage',
        ),
    ]
