# Generated by Django 4.2.3 on 2023-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_audit',
            field=models.BooleanField(default=False),
        ),
    ]
