# Generated by Django 4.2.3 on 2023-09-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_instance_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
