# Generated by Django 4.2.3 on 2023-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
