# Generated by Django 4.2.3 on 2023-10-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cluster_configurations_cluster_gpu_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='dns',
            field=models.CharField(default='huupai@vm-unknown.com', max_length=255),
        ),
    ]
