# Generated by Django 4.2.3 on 2023-09-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instance_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ein',
        ),
    ]
