# Generated by Django 4.2.3 on 2023-09-07 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
