# Generated by Django 4.2.3 on 2023-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_instance_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
