# Generated by Django 4.2.3 on 2023-10-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stripecustomer_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider_paid',
            field=models.BooleanField(default=False),
        ),
    ]
