# Generated by Django 4.2.3 on 2023-09-07 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_instance_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
