# Generated by Django 4.2.3 on 2023-10-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cluster_is_audited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='price',
        ),
    ]
