# Generated by Django 4.2.3 on 2023-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cluster_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='virtualization',
            field=models.BooleanField(default=False),
        ),
    ]
