# Generated by Django 4.2.3 on 2023-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_configurations_cluster_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
