# Generated by Django 4.2.3 on 2023-11-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
